# Model configuration
model:
  name_class: "ResNet50Model"
  params:
    pretrained: True

# Optimization techniques
optimization:
  name_class: "SimpleOptimization"
  params: {}
  result_dir: "models/result/resnet50_sample"


# Data configuration
dataset:
  name_class: "ResNet50DataLoader"
  name: "CIFAR10"
  root: "./data"
  split: "train"
  download: True
  batch_size: 128
  num_workers: 4
  pin_memory: True
  transforms:
    train:
      Resize:
        size: !!python/tuple [224, 224]
      RandomHorizontalFlip:
        p: 0.5
      ToTensor: {}
      Normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
    val:
      Resize:
        size: !!python/tuple [224, 224]
      ToTensor: {}
      Normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
    test:
      Resize:
        size: !!python/tuple [224, 224]
      ToTensor: {}
      Normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]

# Logging configuration
logging:
  log_dir: "./logs/resnet50"
  wandb_project: "model_optimization"
  log_freq: 100